# fly.toml app configuration file generated for casa-table on 2024-02-18T20:04:29-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'casa-table'
primary_region = 'den'

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1

[build]
dockerfile = "Dockerfile"
ignorefile = ".dockerignore"
